#Auto generated by Edalize

TARGET   := test_symbiflow_0

all: $(TARGET).blif


%.blif: test_symbiflow_0.tcl
	yosys -l yosys.log -p "tcl $?"
%.json: test_symbiflow_0.tcl
	yosys -l yosys.log -p "tcl $?"
%.edif: test_symbiflow_0.tcl
	yosys -l yosys.log -p "tcl $?"

clean:
	rm -f $(TARGET).blif $(TARGET).json $(TARGET).edif
